### ISSUE TITLE
Toolkit content styles not reloading on change

### ISSUE THREAD

**Issue by camdagr8** [ReactiumCore/Reactium#19]
Since the toolkit content is loaded in an iframe, the changes to the style sheets aren't propagating and causing a reload even though BrowserSync is calling the bs.stream() function. 

Proposed fix: create a /toolkit/:preview route that loads only the component and use that as the toolkit content iframe source.

**Comment by jamsterdam29** [comment]
I've noticed some styles not reloading when there are in an import as well (not in iframe), although seems intermittent.

**Comment by camdagr8** [comment]
Yeah, I think I've hit that too. So far as I can determine, it's something to do with gulp watch. I haven't decided how to best attack it.

**Comment by jdillick** [comment]
Fixed in Core 722dbde15c6553b76fc684060d13ed324521c3ac
