### ISSUE TITLE
Rendering Top-Level component in SPA

### ISSUE THREAD

**Issue by jamsterdam29** [ReactiumCore/Reactium#39]
Having a little trouble getting a top-level component to render in our SPA.  Code is:
``` 
<body>
    <Component type="DevTools"></Component>
    <Component type="Config"></Component>
    <div id="router"></div>
```

but Config never seems to render.  Any idea on what might be missing?

**Comment by camdagr8** [comment]
@jamsterdam29 

It's more than likely a path issue with where you have the Config component saved in your project. 
For instance if you were trying to mount the Test component that is shipped with the default Reactium build you would do this: 

```jsx
<body>
    <Component type="DevTools"></Component>
    <Component type="Demo/Test"></Component>
    ...
</body>
```

**Comment by camdagr8** [comment]
Closing for lack of feedback
