### ISSUE TITLE
Beautify Module is not IE11 compatible

### ISSUE THREAD

**Issue by jdillick** [ReactiumCore/Reactium#42]
beautify does not do its own transpilation (might only be a problem with css-beautify dependency), and therefore causes (perhaps among other things), a syntax error on arrow functions that are used.

Babel-loader does not transpile on behalf of node_modules (even if you do not exclude them from the loader). We'll need to:

1. select a different isomorphic module, pre-transpiled for IE11, or
2. fork beautify and/or CSS-beautify (or get them to PR in a babel process), or
3. Do beautification server-side (probably not gonna work for static toolkit)

**Comment by camdagr8** [comment]
I'm going to remove beautify and use Prettier instead.
