### ISSUE TITLE
"order" attribute in route causing production error

### ISSUE THREAD

**Issue by jamsterdam29** [ReactiumCore/Reactium#92]
## Issue
The "order" attribute in routes seems to be causing an issue in production builds.  Under **local dev**, no issue is noticed.  However under a static **production** build, the mount function of the target component is called, but the component itself is never loaded/mounted.  No errors are reported in the console.

## Reproduce
When publish with this route, ContentPage is never loaded: 
`{
		path: '/pathtopage',
		order: 10,
		exact: true,
		component: ContentPage,
		load: params => deps.actions.ContentPage.mount(params),
	}`

When publish with this route, ContentPage is loaded as expected: 
`{
		path: '/pathtopage',
		exact: true,
		component: ContentPage,
		load: params => deps.actions.ContentPage.mount(params),
	}`

**Comment by jdillick** [comment]
Unable to reproduce.

```
import ContentPage from './index';
import ContentPage2 from './ContentPage2';
import deps from 'dependencies';

export default [
    {
        path: '/content-page',
        component: ContentPage,
        // Comment out to make order important
        // exact: true
        order: 2,
        load: (params, search) => deps.actions.ContentPage.mount({ params, search }),
    },
    {
        path: '/content-page/:test',
        exact: true,
        component: ContentPage2,
        order: 1,
    },
];
```
