### ISSUE TITLE
Ability to add to webpack entry list

### ISSUE THREAD

**Issue by jamsterdam29** [ReactiumCore/Reactium#96]
Ran into a IE11 issue recently, which I believe was similar to https://github.com/facebook/react/issues/8379.

 I found that setting the react and reactDom load order (partially described in issue 8379) through the entry list resolved the IE11 error.

To do this, I added the following to the webpack override:
```
if (!Array.isArray(newWebpackConfig.entry.main)) {
    newWebpackConfig.entry.main = [
       'react',
       'react-dom',
       newWebpackConfig.entry.main
    ];
    console.log('webpack, entries - %o', newWebpackConfig.entry);
}
```

However, in order to get this to work, I also has to modify .core/index js to work with an existing arry in entry.main

```
if (Array.isArray(webpackConfig.entry.main)) {
     webpackConfig.entry.main.unshift( `webpack-hot-middleware/client?path=/__webpack_hmr&quiet=true`);
}
else {
    webpackConfig.entry.main = [
        `webpack-hot-middleware/client?path=/__webpack_hmr&quiet=true`,
        webpackConfig.entry.main,
     ];
}
```

Can something like that be added to allow array overrides in main.entry?

**Comment by jdillick** [comment]
This is probably possible without changing .core today using `src/app/server/middleware.js`.

**Comment by jdillick** [comment]
Essentially the approach would be to change the `webpack` and `hmr` middlewares according to your needs.

**src/app/server/middleware.js**:

```
const webpack = require('webpack');
const gulpConfig = require('reactium-core/gulp.config');
const webpackConfig = require('reactium-core/webpack.config')(gulpConfig);
const wpMiddlware = require('webpack-dev-middleware');
const wpHotMiddlware = require('webpack-hot-middleware');
let port = gulpConfig.port.proxy;
let pvar = op.get(process.env, 'PORT_VAR', false);
if (pvar) {
  port = op.get(process.env, pvar, port);
} else {
  port = op.get(process.env, 'APP_PORT', port);
  port = op.get(process.env, 'PORT', port);
}
port = Number(port);
const publicPath = `http://localhost:${port}/`;
let compiler;

// Update the webpack configuration to be used for node/express wepback middleware in local dev.
if (process.env.NODE_ENV === 'development') {
    webpackConfig.entry.main.unshift( `webpack-hot-middleware/client?path=/__webpack_hmr&quiet=true`);
    webpackConfig.plugins.push(new webpack.HotModuleReplacementPlugin());
    webpackConfig.output.publicPath = publicPath;
    compiler = webpack(webpackConfig);
}

module.exports = expressMiddlewares => expressMiddlewares.map(mw => {
  if (process.env.NODE_ENV !== 'development') return mw;
  
  switch(mw.name) {
    case 'webpack':
      return {
          name: 'webpack',
          use: wpMiddlware(compiler, {
              serverSideRender: true,
              path: '/',
              publicPath,
          }),
      };

    case 'hmr':
      return {
          name: 'hmr',
          use: wpHotMiddlware(compiler, {
              reload: true,
          }),
      };
    
    default: 
      return mw;
  }
});
```

**Comment by jdillick** [comment]
Didn't test the above, but that'd be the general approach.

**Comment by jamsterdam29** [comment]
Thats for development mode, correct?  In production we aren't using express, in fact the server directory is in the ignore loader list to prevent bundling express.

**Comment by jdillick** [comment]
The part of core you are referencing is only used in local development, to allow webpack to serve live development updates to the browser. The webpack override is used for both. In other words, when you are doing a static build (or node/express production for that matter), that code is not in play.

Your updates to webpack override for the static build should work fine.
